import = [
    "~/.config/alacritty/themes/themes/catppuccin-mocha.toml"
]

[window]
dimensions = {columns=120,lines=30}
opacity = 0.9

[font]
size = 12.0

[font.bold]
family = "MesloLGS NF"
style = "Bold"

[font.bold_italic]
family = "MesloLGS NF"
style = "Bold Italic"

[font.italic]
family = "MesloLGS NF"
style = "Italic"

[font.normal]
family = "MesloLGS NF"
style = "Regular"

[keyboard]
bindings = [
  #  spawn a new instance of Alacritty in the current working directory by pressing
   { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" },
   { key = "Return", mods = "Control", chars = "\u001b[13;5u"},
   { key = "Return", mods = "Shift", chars = "\u001b[13;2u"},
]

[[hints.enabled]]
regex = "[^ ]+\\.rs:\\d+:\\d+"
command = { program = "code", args = [ "--goto" ] }
mouse = { enabled = true }
